baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "KuberGuide - Learn to build self-hosted Kubernetes cluster"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/kubernetes-go/getting-started/edit/main/guide/content/"
  description = "Documentation for Hugo Learn Theme"
  author = "Wu Jun"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableLandingPageButton = true
  disableMermaid = false
  customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  titleSeparator = "::"
  themeVariant = "blue"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en.params]
title = "KuberGuide - Learn to build self-hosted Kubernetes cluster"
weight = 1
languageName = "English"
landingPageURL = "/en"
landingPageName = "<i class='fas fa-home'></i> Home"
